<?php


/**
 * Implements template_preprocess().
 */
function adc_accessibe_preprocess(&$variables) {
  $settings = \Drupal::config('adc_accessibe.settings');

  if (isset($settings)) {
    $variables['accessibe_enabled'] = $settings->get('enabled');
  }
}

/**
 * Implements hook_page_bottom().
 */
function adc_accessibe_page_bottom(array &$page_bottom) {
  $settings = \Drupal::config('adc_accessibe.settings');

  if (!$settings->get('enabled')) {
    return;
  }

  $page_bottom['accessibe'] = [
    '#type'  => 'html_tag',
    '#tag'   => 'script',
    '#value' => $settings->get('script'),
  ];
}